version: '3'
services:
  # The Application
  flaskapp:
    build:
      context: ./
      dockerfile: flask.Dockerfile
    ports:
      - "5000:5000"
  nginx:
    build: 
      context: ./
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"