NAME = ria-service-intent-processing
IMAGE_NAME = ria-service-intent-processing
PROJECT_TYPE = python-lambda
BUILDER_IMAGE_VERSION = 3.7
PYTHON_LAMBDA_BUILD_MODULE = lambdas/intent_processing/ria_intent_processing
PYTHON_LAMBDA_TEST_MODULE = lambdas/intent_processing/ria_intent_processing
