description: |
  Building their projects with CircleCI.
version: 2.1
executors:
  default:
    description: |
      Custom Docker image with docker pyton3.7 to build library
    docker:
    - image: circleci/python:3.7.2
jobs:
  build:
    description: |
      Build libs
    executor: default
    steps:
    - checkout
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - restore_cache:
        key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
    - run:
        command: |
          sudo mkdir -p build || true
          sudo pip install -r requirements.txt -t build/
        name: Build_libs
    - save_cache:
        key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
        paths:
          - '/usr/local/bin'
    - run:
        name: Zip_files
        command: |  
          cp -r lambdas/intent_processing/ria_intent_processing build/          
          cd build/ && zip -r {{ checksum "../requirements.txt" }}.zip ./*
          ls -ltr