description: |
  Building their projects with CircleCI.
version: 2.1
executors:
  docker_python37:
    description: |
      Custom Docker image with docker pyton3.7 to build library
    docker:
    - image: circleci/python:3.7.2
  docker_awscli:
    docker:
      - image: alpine:latest
jobs:
  build:
    description: |
      Build libs
    executor: docker_python37
    steps:
    - checkout
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - restore_cache:
        key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
    - run:
        name: Build_libs
        command: |
          sudo mkdir -p build || true
          sudo pip install -r requirements.txt -t build/
          ls -ltr build/
    - save_cache:
        key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
        paths:
          - '/usr/local/bin'
    - run:
        name: Zip_files
        command: |       
          ZIP_NAME=`md5sum requirements.txt | awk '{ print $1 }'`
          sudo cp -r lambdas/intent_processing/ria_intent_processing build/          
          cd build/ && sudo zip -r $ZIP_NAME.zip ./*
          ls -ltr
  deliver_to_S3:
    description: |  
      Build libs
    executor: docker_awscli
    steps:
    - run:
        name: push_zip_to_s3
        command: |
          echo "hello"
          echo "s3 key: " ${s3_put_key} ${s3_put_secret}
workflows:
  version: 2
  build-delivertoS3:
    jobs:
      - build
      - deliver_to_S3:
          requires:
            - build
