description: |
  Building their projects with CircleCI.
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@x.y
executors:
  docker_python37:
    description: |
      Custom Docker image with docker pyton3.7 to build library
    docker:
    - image: circleci/python:3.7.2
  docker_awscli:
    docker:
      - image: alpine:latest
jobs:
  build:
    description: |
      Build libs
    executor: docker_python37
    steps:
    - checkout
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - restore_cache:
        key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
    - run:
        name: Build_libs
        command: |
          sudo mkdir -p build || true
          sudo pip install -r requirements.txt -t build/
          ls -ltr build/
    - save_cache:
        key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
        paths:
          - '/usr/local/bin'
    - run:
        name: Zip_files
        command: |       
          ZIP_NAME=`md5sum requirements.txt | awk '{ print $1 }'`
          sudo cp -r lambdas/intent_processing/ria_intent_processing build/          
          cd build/ && sudo zip -r $ZIP_NAME.zip ./*
          cd .. && sudo mkdir -p workspace
          sudo cp -r build workspace
    - persist_to_workspace:
        root: workspace
        paths:
          - build
  deliver_to_S3:
    description: |  
      Build libs
    executor: docker_awscli
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - aws-s3/copy:
        name: push_zip_to_s3
        arguments: '--dry-run'
        aws-access-key-id: ${s3_put_key}
        aws-region: us-east-1
        aws-secret-access-key: ${s3_put_secret}
        from: /tmp/workspace/build/*.zip
        to: s3://${bucket_name}
#          echo "s3 key: " ${s3_put_key} ${s3_put_secret}
workflows:
  version: 2
  build-delivertoS3:
    jobs:
      - build:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - circleci-project-setup
      - deliver_to_S3:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - circleci-project-setup
          requires:
            - build
