description: |
  Building their projects with CircleCI.
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
executors:
  docker_python37:
    description: |
      Custom Docker image with docker pyton3.7 to build library
    docker:
    - image: circleci/python:3.7.2
  docker_awscli:
    docker:
      - image: 'cimg/python:3.6'
jobs:
  build:
    description: |
      Build libs
    executor: docker_python37
    steps:
    - checkout
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - restore_cache:
        key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
    - run:
        name: Build_libs
        command: |
          sudo mkdir -p build || true
          sudo pip install -r requirements.txt -t build/
          ls -ltr build/
    - save_cache:
        key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
        paths:
          - '/usr/local/bin'
    - run:
        name: Zip_files
        command: |       
          REQUIREMENT_MD5CHECKSUM=`md5sum requirements.txt | awk '{ print $1 }'`
          sudo cp -r lambdas/intent_processing/ria_intent_processing build/          
          cd build/ && sudo zip -r $REQUIREMENT_MD5CHECKSUM.zip ./*
          cd .. && sudo mkdir -p workspace
          sudo cp -r {build,requirements.txt} workspace
    - persist_to_workspace:
        root: workspace
        paths:
          - build
          - requirements.txt
  deliver_to_S3:
    description: |  
      Build libs
    executor: docker_awscli
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: set env REQUIREMENT_MD5CHECKSUM
        command: |
          ls -ltr /tmp/workspace/
          export REQUIREMENT_MD5CHECKSUM=$(md5sum /tmp/workspace/requirements.txt | awk '{ print $1 }')
          echo $REQUIREMENT_MD5CHECKSUM
    - aws-s3/copy:
        aws-access-key-id: s3_put_key
        aws-region: s3_region
        aws-secret-access-key: s3_put_secret
        from: /tmp/workspace/build/$(md5sum /tmp/workspace/requirements.txt | awk '{ print $1 }').zip
        to: s3://${bucket_name}

workflows: 
  version: 2
  build-delivertoS3:
    jobs:
      - build:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - circleci-project-setup
      - deliver_to_S3:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - circleci-project-setup
          requires:
            - build
          context: ForAllProjects  